services:

  web:
    build:
      context: .
      args:
        TESTING: 'true'
        EMAIL: mhanberry1@gmail.com
        DOMAINS: maastalent.com,www.maastalent.com,api.maastalent.com
    ports:
      - 80:80
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
